"""empty message

Revision ID: 00431f19f01d
Revises: 662a6b7abb7e
Create Date: 2020-04-16 22:56:58.252290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00431f19f01d'
down_revision = '662a6b7abb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
