"""empty message

Revision ID: 3e88db651632
Revises: 6bdb0dffce95
Create Date: 2020-04-16 07:21:02.411172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e88db651632'
down_revision = '6bdb0dffce95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
