"""empty message

Revision ID: 4abdb197fcf2
Revises: eff921208d31
Create Date: 2020-04-16 18:24:41.277620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abdb197fcf2'
down_revision = 'eff921208d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
